### ISSUE TITLE
Typo: Bytes to Bits

### ISSUE THREAD

**Issue by brandonfosso** [rsokl/Learning_Python#109]
Hi, I think I spotted a typo in the [understanding numerical precision](https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Basic_Objects.html#Understanding-Numerical-Precision) section of module 2. Last line in the first paragraph, 8 bytes should be 64 bits.

Really enjoying the book, thanks for writing!

**Comment by rsokl** [comment]
You are right! Thank you.

**Comment by rsokl** [comment]
This will be fixed in the next HTML update.
