### ISSUE TITLE
Simple Grammar Typo

### ISSUE THREAD

**Issue by brandonfosso** [rsokl/Learning_Python#119]
On the page [Introducing the ND-array](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/IntroducingTheNDarray.html) there is a typo just after the second code block. The line reads 'This object is belongs to ...' It should probably say 'This object belongs to ...'

**Comment by brandonfosso** [comment]
Happy to help :) I am slowly working my way through your book and am really liking it. Thanks for doing it!

**Comment by rsokl** [comment]
Glad to hear it! Please let me know if you have any particular feedback about the material - I am always looking to improve the site.
