### ISSUE TITLE
Error in section "Introducing the ND-array" 

### ISSUE THREAD

**Issue by apezzotti86** [rsokl/Learning_Python#126]
There is an error in the below text. Taking mean value over three distinct columns should use axis = 0. If you manually compute the averages, axis = 1 takes the average over rows. 

Let’s take the mean value over the three distinct columns in our data:

>>> np.mean(x, axis=1)
array([ 1.,  4.,  7.])

**Comment by rsokl** [comment]
Thank you for reporting this! This is now fixed (2a81ef999e6b16c991d87618aa5096ad6b35eb4a).
