### ISSUE TITLE
New Module: Odds & Ends

### ISSUE THREAD

**Issue by rsokl** [rsokl/Learning_Python#15]
Precise content to be included here is up for debate

### Matplotlib
- [x] Object-oriented interface only (explicit use of fig/ax objects)
- [x] Plotting in notebook mode (this should be the main mode of plotting)
- [x] Basic plotting, color, line-style, axis labels, titles
- [x] Error-bars and fill-between error regions
- [x] Multiple plots
- [x] Plotting images 
- [x] Saving figures

### File I/O
- [x] Introduce the `open` context manager
- [x] Basics usage of the yielded file object: read, readline, iterations, write, etc.
- [x] NumPy I/O functionality
- [x] working with paths: `pathlib.Path`

### String Formatting (??)
- [ ] f-strings, etc.

### Basic of modules (??)
- [x] `__init__.py` and creating your own Python package
- [x] dirt-simple `setup.py` template and demonstration of `python setup.py install/develop`

**Comment by davidmascharka** [comment]
This is inactive and the `format` function is already covered; f-strings could fit in there but they're (relatively) minor so I'm going to close this. An f-string-specific issue could be opened if that's a real need.
