### ISSUE TITLE
Typo in Slicing Section

### ISSUE THREAD

**Issue by RaviChandraVeeramachaneni** [rsokl/Learning_Python#157]
Slicing Section -> Examples (https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/SequenceTypes.html#Slicing)

Exact Location : Example 3 in Code Examples. 

<img width="505" alt="Screen Shot 2020-08-10 at 7 07 26 PM" src="https://user-images.githubusercontent.com/14807933/89849160-bd611b80-db3c-11ea-97d7-e02e78de6e44.png">

Typo : Comment on the Example says **# start:1, stop:5, step:2**
Expected : **start:0**

**Comment by rsokl** [comment]
Thanks for catching this!
