### ISSUE TITLE
Can enhance the Example or Change the example to avoid potential Syntax Warning. 

### ISSUE THREAD

**Issue by RaviChandraVeeramachaneni** [rsokl/Learning_Python#159]
In one of the example where **is** is used instead of **==** we are getting a potential Syntax Warning. This might be confusing sometimes. So we can enhance the example of why it happens or we can simply change that to use **==** instead. 

Exact location : Generator & Comprehensions Section -> Reading Comprehension Exercise Solution -> Translating a For-Loop (Below screenshot from website):

![Screen Shot 2020-08-12 at 3 44 42 PM](https://user-images.githubusercontent.com/14807933/90075637-c07e1800-dcb2-11ea-9390-daa570e68903.png)

So the above code mentioned produces below Warning (screenshot from my system): 

![Screen Shot 2020-08-12 at 3 46 49 PM](https://user-images.githubusercontent.com/14807933/90075775-0aff9480-dcb3-11ea-96d9-54958459db7e.png)

Instead we can use **==** instead of **is** operator to have more cleaner interpretation (screenshot from my system):

![Screen Shot 2020-08-12 at 3 47 06 PM](https://user-images.githubusercontent.com/14807933/90075787-1488fc80-dcb3-11ea-8549-2a61c7d4bd10.png)

Please let me know if this makes sense and also if there is an opportunity I would like to submit a PR for this and in future few more additions. 

Thanks in Advance.

**Comment by rsokl** [comment]
Thanks for pointing this out! I would be happy to have this PR :)

**Comment by rsokl** [comment]
Oh, and I should be more specific - the example should be using `==` instead of `is`

**Comment by RaviChandraVeeramachaneni** [comment]
Thanks Ryan for the opportunity. I will be submitting the PR soon.
However the guidelines on the git repo says that I need to be added as a
contributor to make the change. Could you please add me as a contributor to
the project.

My email Id : vrc0503@gmail.com

Thanks in Advance.

Regards,
Ravi Chandra Veeramachaneni

**Comment by rsokl** [comment]
Hi @RaviChandraVeeramachaneni - I need to update those guidelines. The preferred method is for you to [fork the repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) and make a PR from your fork. 

I apologize for the confusion / inconvenience

**Comment by RaviChandraVeeramachaneni** [comment]
Thanks Ryan for the clarification.

I did that and made a PR (https://github.com/rsokl/Learning_Python/pull/160
).

Could you let me know some guidelines on how to become a potential
contributor to the project and make it on to the contributor / reviewer
list.

Thanks in Advance.

Regards,
Ravi Chandra Veeramachaneni

**Comment by rsokl** [comment]
Thanks for the PR @RaviChandraVeeramachaneni 

I don't have formal guidelines - if you make several contributions to PLYMI, I would happily add you as a contributor :)

**Comment by rsokl** [comment]
closed by #160
