### ISSUE TITLE
Use TypeVar instead of Any for type-hint exercise

### ISSUE THREAD

**Issue by tbazin** [rsokl/Learning_Python#199]
Hi!

Nice project :)
Was just browsing through and I saw the solution to the assignment in Module 5 [here](https://www.pythonlikeyoumeanit.com/Module5_OddsAndEnds/Writing_Good_Code.html#Reading-Comprehension-Solutions) uses explicit `Any` annotations where using a generic would seem more appropriate and better from a pedagogical perspective (I believe explicit Any annotations should generally be avoided). But I get that generics may be considered too advanced for introductory classes.

The solution would then be:
```python
from typing import Any, Sequence, Tuple, TypeVar

T = TypeVar('T')

def get_first_and_last(x: Sequence[T]) -> Tuple[T, T]:
    """Returns the first and last elements of `x`. `x` is
    assumed to be non-empty
    """
    return (x[0], x[-1])
```

**Comment by rsokl** [comment]
Hi @tbazin ! Thanks for the write-up. You are certainly correct that this is the appropriate place for a `TypeVar`. My concern, though - as you highlighted - is that this might be a bit too complicated for the reader. I'll mull it over.
