### ISSUE TITLE
Code block formatting issue

### ISSUE THREAD

**Issue by rsokl** [rsokl/Learning_Python#34]
There seems to be a problem with mix-and-match style code blocks that incorporate multiline comments mixed with console-style inputs

```python
# 1
>>> "yo"
yo
```

versus

```python
# 1
# 2
>>> "yo"
  File "<ipython-input-29-41bcffd77fef>", line 3
    >>> "yo"
     ^
SyntaxError: invalid syntax
```

Can others verify this behavior? Does this seem like a major issue? @AFederici when you were working through the content, did you naturally just copy the input-lines, denoted by `>>>`, or did were you wanting to copy the entire code blocks?

I'm concerned that readers getting this syntax error will not realize that they can just delete the multi-line comment, as this is very obscure.

**Comment by davidmascharka** [comment]
Did you still want to add that note [in here](https://www.pythonlikeyoumeanit.com/Module1_GettingStartedWithPython/SiteFormatting.html)?

**Comment by rsokl** [comment]
I will add a note about this
