### ISSUE TITLE
Proofreading fixes

### ISSUE THREAD

**Issue by davidmascharka** [rsokl/Learning_Python#77]
Feel free to add to this with minor text changes that can get pushed later.

- [x] "E.g., in Linux you can add the following alias to you ~/.bashrc file" should be **your** bashrc [here](https://www.pythonlikeyoumeanit.com/Module1_GettingStartedWithPython/Installing_Python.html)

- [x] "To start the IPython console, open your terminal (Mac/Linux) or cmd.exe (Windows), type ipython into it, and hit <Enter>. You should see the following display on your screen:" at the beginning of [this section](https://www.pythonlikeyoumeanit.com/Module1_GettingStartedWithPython/Informal_Intro_Python.html) reads a little awkardly. Rephrasing this would be good.

**Comment by rsokl** [comment]
oh! I'll make these right now

**Comment by rsokl** [comment]
Closed with #79
